### PR TITLE
#198 - Add support for async data source

### PR DESCRIPTION
**Pull request by samlanning**
This PR addresses #198, and allows a callback function as a new type of data source.

Rebased on top of develop, replaces #210

### CODE REVIEW

**Comment by running-coder** [comment]
Hey Sam, I've merged the pull request but after taking a closer look at it, it seemed there was a more optimal way to achieve the result. Your solution works but adds branch to the "gather data+parse" process which then makes it more complex.

Instead I've opted to use the `$.Deferred` object that jQuery provides. Using this doesn't modify the data flow, adds all the functinality that Deferred provides and just requires the source.group.data to create a Deferred object and return it.

```javascript
data: function () {

    var deferred = $.Deferred();

    setTimeout(function () {
        deferred.resolve(data)
    }, 2000);

    deferred.always(function () {
        console.log('yay! :D')
    });

    return deferred;
}
```

**Comment by samlanning** [comment]
Awesome thanks =)

**Comment by gs-smuthyam** [comment]
Hey Sam,

was trying to use this method, somehow I'm not able to get what I'm looking for: any suggestions on this ? Below is what my code looks like

source:{
                data: function (query) {

                    var _deferred = j$.Deferred();

                    <<AJAX.Remote.Invocation>>.done((evt)=> {
                            _deferred.resolve(evt['data']);
                        }).fail((evt)=> {
                            _deferred.reject(evt);
                        });
                    return _deferred;
                }

**Comment by gs-smuthyam** [comment]
Ok, I saw the change was added in the latest version to handle this. Thanks.

**Pull request merged**
