### PR TITLE
submit a different value than is being displayed

### PR DESCRIPTION
**Pull request by seltix5**
with this new option it is now possible to set a template for the return value.

### CODE REVIEW

**Comment by seltix5** [comment]
this is also a better alternative to this situations : 
https://github.com/running-coder/jquery-typeahead/issues/168

**Comment by running-coder** [comment]
hey @seltix5 indeed that would be a nice option to have and avoid manual operations! Here are a few points:
- can you set the merge branch to be `develop`? The code on `master` is the latest released tag
- can you run `gulp` to also generate the .min file
- can you add 1-2 tests to validate this integration for now and the future

**Comment by seltix5** [comment]
hi,
i wold do that but i dont know how :/ i'm a notepad++ person :P
do i need to install something?
i'm new with GitHub

**Comment by running-coder** [comment]
np I'll handle the remaining parts inside #304, thanks for the PR

**Pull request merged**
