### PR TITLE
fix IE8 issues, set obj by OnSubmit if typing value or using hint, use t...

### PR DESCRIPTION
**Pull request by MiArktos**
Hey Running-coder,
first of all thank you very match to fix the issue with trim and
adding  obj to the callback function OnSubmit.
I fixed the other small issue with IE8 so I can also use the option hint with IE8.
The main issue with the IE8 is the different behavior of propertychange
event in IE8 and the input event in the other browsers.
There is a very good explanation of this on
http://benalpert.com/2013/06/18/a-near-perfect-oninput-shim-for-ie-8-and-9.html
and a jquery plugin for that.
But I assume I can't use both plugins together so I only used the idea.

I tried to make the fix effects only the IE8 and not to interfere with the other browsers.
But I had to call the clone function with the parameter false instead of true.
I have tested the fix with IE8, IE11 and the current Firefox an Chrome browser.
So far it seems there is no negative effects of this change.
The variable obj in the OnSubmit function isn't set if I only type the value
or use the hint function. So I fixed this too.
I added the keycode 9 to the hint function so a can use the tab to select the hint.
I hope my changing's don't create new issues and they are convenient.I hope my changing's don't create new issues and they are convenient.

### CODE REVIEW

**Comment by running-coder** [comment]
Hey MiArktos,

thanks for the comments and contribution!
I'll check your motifs as soon as I can.

Thanks

**Comment by MikeHoffert** [comment]
I just want to second the setting of the `obj` in `onSubmit` when the hint completed. I can't use the hint without this.

**Comment by MikeHoffert** [comment]
Oh, I didn't realize that I had commented on a pull request and not an open issue. I tried the master, but it doesn't seem to display the hint at all in a typeahead where it previously did. This was with a typeahead where I'm selecting objects in the form `{name: "...", address: "...", id: 123}` and need to show the name/address, but submit the ID.

The stable version (from your website) works for getting the ID from `onSubmit`, but hints do not. Current master (as of 66a96d2abb) does not display the hint at all and pressing right/tab does nothing.

**Comment by MikeHoffert** [comment]
Never mind, I'm dumb. The pull request does work.

**Pull request merged**
